### ISSUE TITLE
timestamp 관련 데이터를 입력시 'Malformed communication packet.' 에러 발생건

### ISSUE THREAD

**Issue by lhj12ps** [yellow-w/theGreatest6#101]
1) front에서 입력받고 백으로 보냄 -> 백에서 req.body로 받음
2) sql 구문으로 데이터를 입력하려고하면 'Malformed communication packet.' 오류 발생

[ 코드 ]

 ```
const {category, xrated, title, place, showCast1, showCast2, showDirector,showCompany,showContent,showMonth,showDate,showHour} = req.body

const sqlShow = `INSERT INTO shows(
        show_title,
        show_category_idx,
        show_xrated,
        show_company,
        show_director,
        show_like,
        show_date_open,
        show_content
        ) VALUES(
            ?,?,?,?,?,1,
            ?,
            ?)`

let now = new Date() //현재 시간을 받아오는 함수
let thisYear = now.getFullYear() //올해만 뽑아오는 함수 2022

const timestamp = `${thisYear}-${showMonth}-${showDate} ${showHour}:00`
const prespareShow = [title,category,xrated,showCompany,showDirector,timestamp,showContent]
```

[ 백 에러코드 ]
```
at PromisePool.execute (/Users/hancoco/workspace/theGreatest6/back/node_modules/mysql2/promise.js:359:22)
    at exports.showWrite (/Users/hancoco/workspace/theGreatest6/back/routes/show/program/programController.js:43:41)
    at Layer.handle [as handle_request] (/Users/hancoco/workspace/theGreatest6/back/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/hancoco/workspace/theGreatest6/back/node_modules/express/lib/router/route.js:137:13)
    at Immediate.<anonymous> (/Users/hancoco/workspace/theGreatest6/back/node_modules/multer/lib/make-middleware.js:53:37)
    at processImmediate (node:internal/timers:468:21) {
  code: 'ER_MALFORMED_PACKET',
  errno: 1835,
  sql: 'INSERT INTO shows(\n' +
    '        show_title,\n' +
    '        show_category_idx,\n' +
    '        show_xrated,\n' +
    '        show_company,\n' +
    '        show_director,\n' +
    '        show_like,\n' +
    '        show_date_open,\n' +
    '        show_content\n' +
    '        ) VALUES(\n' +
    '            ?,?,?,?,?,1,\n' +
    '            ?,\n' +
    '            ?)',
  sqlState: 'HY000',
  sqlMessage: 'Malformed communication packet.'
}
```

**Comment by lhj12ps** [comment]
갑자기 입력이 되어버림. 뭔가 저장을 늦게했나봐요.
1) foregine key인 s_category에 데이터를 넣음.
2) 필요없는 값은 prepare에 넣지않고 sql 구문에 임의로 값을 넣음.

결론
timestamp값은 형식만 맞춰주면 변수상태(임의로 만든 timestamp)를 넣어줘도 작동한다.
