### ISSUE TITLE
회원가입시 db 에러

### ISSUE THREAD

**Issue by o-haa** [yellow-w/theGreatest6#92]
Error: The user specified as a definer ('%'@'localhost') does not exist
    at PromisePool.execute (/Users/oo_ha/workspace/project/team6/theGreatest6/back/node_modules/mysql2/promise.js:359:22)
    at exports.signUp (/Users/oo_ha/workspace/project/team6/theGreatest6/back/routes/account/member/memberController.js:62:31)
    at Layer.handle [as handle_request] (/Users/oo_ha/workspace/project/team6/theGreatest6/back/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/oo_ha/workspace/project/team6/theGreatest6/back/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/oo_ha/workspace/project/team6/theGreatest6/back/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/oo_ha/workspace/project/team6/theGreatest6/back/node_modules/express/lib/router/layer.js:95:5)
    at /Users/oo_ha/workspace/project/team6/theGreatest6/back/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/oo_ha/workspace/project/team6/theGreatest6/back/node_modules/express/lib/router/index.js:341:12)
    at next (/Users/oo_ha/workspace/project/team6/theGreatest6/back/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/oo_ha/workspace/project/team6/theGreatest6/back/node_modules/express/lib/router/index.js:174:3) {
  code: 'ER_NO_SUCH_USER',
  errno: 1449,
  sql: 'INSERT INTO user (user_id,user_password,user_nickname) VALUES (?,?,?)',
  sqlState: 'HY000',
  sqlMessage: "The user specified as a definer ('%'@'localhost') does not exist"
} 회원가입 에러 발생

**Comment by yellow-w** [comment]
우선 올려주신 에러 메세지로 미루어 보아 DB 이벤트 이슈로 확인됩니다.
구두로 피드백 드렸으니 확인 후 해결되지 않으면 상황 공유 부탁드립니다.
